# Generated by Django 4.0.1 on 2022-01-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_segundomodelo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='segundomodelo',
            table='sdegundo_modelo',
        ),
    ]
