# Generated by Django 4.0.1 on 2022-02-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0003_alter_segundomodelo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='segundomodelo',
            table='segundo_modelo',
        ),
    ]
