# Generated by Django 4.0.2 on 2022-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0004_alter_segundomodelo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primermodelo',
            name='campo_uno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='primermodelo',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
